name: unit-testing
on:
  workflow_dispatch:
  push:
    branches:
      - "practice/*"
      
jobs:
  unit-testing:
    runs-on: ubuntu-latest
    name: unit testing
    steps:
      - name: checkout repo
        uses: actions/checkout@v6
      - name: setup node js 
        uses: actions/setup-node@v6
        with:
          node-version: 24
            
      - name: install dependencies
        run: npm install
      - name: unit testing
        run: npm test
      - name: archive test result
        uses: actions/upload-artifact@v4
        with:
          name: test results 
          path: test-results.xml
        

